# Generated by Django 4.0.4 on 2022-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qd_music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank='true', null='true', upload_to='thumbnails/'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image_alt',
            field=models.CharField(default='STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='show_date',
            field=models.CharField(max_length=200, null='true'),
            preserve_default='true',
        ),
    ]
