# Generated by Django 4.0.4 on 2022-06-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qd_music', '0003_remove_post_image_remove_post_image_alt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='band',
        ),
    ]
