# Generated by Django 4.0.4 on 2022-06-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qd_music', '0004_rename_title_post_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(max_length=200, null='true', unique=True),
            preserve_default='true',
        ),
    ]
