# Generated by Django 4.0.4 on 2022-06-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qd_music', '0005_post_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='band',
            new_name='title',
        ),
    ]
